---
title: "Exploring statevar space"
output: github_document
date: 10/7/2019
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(dplyr)
library(ggplot2)
```

Downloading the data files used in Elita Baldridge's dissertation and White et al 2012, to see what the range of S and N in those data sets was. 

```{r download Baldridge data}

if(!dir.exists(here::here("reports", "datasets"))) {
  dir.create((here::here("reports", "datasets")))
}

if(FALSE) {
  
  download.file(url = "https://raw.githubusercontent.com/weecology/sad-comparison/master/sad-data/mcdb_spab.csv", destfile = here::here("reports", "datasets", "mcdb_spab.csv"))
  
  download.file(url = "https://raw.githubusercontent.com/weecology/sad-comparison/master/sad-data/bbs_spab.csv", destfile = here::here("reports", "datasets", "bbs_spab.csv"))
  
  download.file(url = "https://raw.githubusercontent.com/weecology/sad-comparison/master/sad-data/gentry_spab.csv", destfile = here::here("reports", "datasets", "gentry_spab.csv"))
  
  download.file(url = "https://raw.githubusercontent.com/weecology/sad-comparison/master/sad-data/fia_spab.csv", destfile = here::here("reports", "datasets", "fia_spab.csv"))
  
}

```

Condit et al data: https://datadryad.org/stash/dataset/doi:10.15146/R3MM4V 
Condit, Richard et al. (2018), Tree species abundance through time in tropical forest census plots, Panama, DataONE, Dataset, https://doi.org/10.15146/R3MM4V


```{r get Condit data}

conditNames <- c("bci", "cocoli", "sherman")

conditDat <- list()

for(i in 1:3) {
  conditDat[[i]] <- read.csv(here::here("reports", "datasets", "condit_raw", paste0(conditNames[i], "AbundTable.csv")), stringsAsFactors = F) %>%
    select(-Family, -Authority) %>%
    tidyr::gather(-Latin, key = "year", value = "abundance") %>%
    mutate(year = as.integer(substr(year, 2, 5))) %>%
    rename(species = Latin) %>%
    filter(abundance > 0)
}

names(conditDat) <- conditNames

conditDat <- bind_rows(conditDat, .id = "dataset_name")


```


```{r load Baldridge data}

sitenames <- c("mcdb", "gentry", "fia", "bbs")

datasets <- list()

for(i in 1:4) {
  
  datasets[[i]] <- read.csv(here::here("reports", "datasets", paste0(sitenames[i], "_spab.csv")), header = F,skip =2, stringsAsFactors = F)
  
  colnames(datasets[[i]]) <- c("site", "year", "species", "abundance")
  
  names(datasets)[i] <- sitenames[i]
  
  head(datasets[[i]])
  
  uniqueyears <- datasets[[i]] %>%
    select(site, year) %>%
    distinct() %>%
    group_by(site) %>%
    summarize(nyears = n()) %>%
    ungroup() %>%
    filter(nyears > 1)
  
  if(nrow(uniqueyears) > 1) {
    print(paste0("Some ", sitenames[i], " sites have more than one year"))
  }
  
  datasets[[i]] <- datasets[[i]] %>%
    mutate(species = as.character(species))
}

alldat <- bind_rows(datasets, .id = "dataset_name") %>%
  mutate(year = 1800)

alldat <- bind_rows(alldat, conditDat)

```

### Statevars

```{r process statevars, fig.width = 5, fig.height = 20}

statevars <- alldat %>%
  group_by(dataset_name, site, year) %>%
  summarize(nspp = n(),
            nind = sum(abundance)) %>%
  ungroup() %>%
  mutate(year = as.factor(year))

statevars_plot <- ggplot(data = statevars, aes(x = nspp, y = nind, color = year)) +
  geom_point() +
  theme_bw() +
  facet_grid(rows = vars(dataset_name), scales = "free", switch = "y") +
  scale_color_viridis_d(end = .8)

statevars_plot

```

### Average abundance (N/S)

```{r mean abund plots, fig.width = 5, fig.height = 20}

meanabund <- statevars %>%
  mutate(mean_abund = nind / nspp) 

meanabund_plot <- ggplot(data = meanabund, aes(x = 0, y = mean_abund)) +
  geom_boxplot() +
  theme_bw() +
  facet_grid(rows = vars(dataset_name), scales = "free", switch = "y")

meanabund_plot

```