---
title: "Raw area of deviation"
author: "Renata Diaz"
date: "8/22/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(ggplot2)
library(meteR)
library(dplyr)
library(scads)

nsamples <- 300

save_samples <- F

load_samples <- T

```

```{r get some data, echo = F}

portal_data <- isds::get_toy_portal_data(download=T, years = c(1990:1995))

portal_sad <- portal_data %>%
  select(species) %>%
  group_by(species) %>%
  summarize(abund = n()) %>%
  ungroup() %>%
  select(abund) %>%
  arrange(abund) %>%
  as.matrix() %>%
  as.vector()

nspp = length(portal_sad)
nind = sum(portal_sad)

portal_sad <- data.frame(
  abund = portal_sad,
  source = "emp"
)


```

```{r make and plot extreme cases, echo = F}

flat <- portal_sad %>%
  mutate(source = "flat",
         abund = generate_even_sad(abund))

stepwise <- portal_sad %>%
  mutate(source = "stepwise",
         abund = generate_stepwise_sad(abund))

expesque <- portal_sad %>%
  mutate(source = "exp", 
         abund = generate_exponential_sad(abund))

prec <- portal_sad %>%
  mutate(source = "precipice",
         abund = generate_precipice_sad(abund))

all_sads <- bind_rows(portal_sad, flat, stepwise, expesque, prec) %>%
  group_by(source) %>%
  mutate(rank = row_number()) %>%
  ungroup()

all_sads_plot <- ggplot(data = all_sads, aes(x = rank, y = abund, color = source)) +
  geom_point() +
  facet_wrap(source ~ .) +
  theme_bw() +
  theme(legend.position = "none")

all_sads_plot

```


```{r draw and plot fs and mete corpuses}
if(load_samples) {
  load(here::here("reports", "sensitivity_stash.Rds"))
} else {
set.seed(1977)

mete_samples <- sample_METE(s = nspp, n = nind, nsamples = nsamples, distinct = TRUE) %>%
  tidyr::gather(key = "sim", value = "abund") %>%
  dplyr::mutate(sim = as.integer(substr(sim, 2, nchar(sim))),
                source = "mete")

fs_samples <- sample_feasibleset(s = nspp, n = nind, nsamples = nsamples, distinct = TRUE) %>%
  tidyr::gather(key = "sim", value = "abund") %>%
  dplyr::mutate(sim = as.integer(substr(sim, 2, nchar(sim))),
                source = "fs")

sim_sads <- bind_rows(mete_samples, fs_samples) %>%
  group_by(sim, source) %>%
  mutate(rank = row_number()) %>%
  ungroup()

if(save_samples) {
  save(sim_sads, file = here::here("reports", "sensitivity_stash.Rds"))
}
}

sample_plot <- ggplot(data = sim_sads, aes(x = rank, y = abund)) +
  geom_point(alpha = 0.05) +
  theme_bw() +
  facet_grid(cols = vars(source))

sample_plot

```

```{r sad area of difference}

aod <- sim_sads %>%
  group_by(sim, source) %>%
  summarize(emp = sum(abs(sort(abund) - sort(filter(all_sads, source == "emp")$abund))),
            flat = sum(abs(sort(abund) - sort(filter(all_sads, source == "flat")$abund))),
            stepwise = sum(abs(sort(abund) - sort(filter(all_sads, source == "stepwise")$abund))),
            exp = sum(abs(sort(abund) - sort(filter(all_sads, source == "exp")$abund))),
            precipice = sum(abs(sort(abund) - sort(filter(all_sads, source == "precipice")$abund)))) %>%
  ungroup() %>%
  tidyr::gather(-sim, -source, key = "comparison_source", value = "aod")

sim_bank <- sim_sads %>%
  mutate(sim = 1+ ((sim + 1) %% nsamples)) %>%
  rename(new_sim = sim)


sim_aod <- sim_sads %>%
  group_by(sim, source) %>%
  summarize(z_fs = sum(abs(sort(abund) - sort(filter(sim_bank, source == "fs", new_sim == sim)$abund))), 
           z_mete = sum(abs(sort(abund) - sort(filter(sim_bank, source == "mete", new_sim == sim)$abund)))) %>%
  ungroup() %>%
  tidyr::gather(-sim, -source, key = "comparison_source", value = "aod")


aod <- bind_rows(aod, sim_aod)


aod_plot <- ggplot(data = aod, aes(x = comparison_source, y = aod, color = comparison_source)) +
  geom_boxplot() +
  theme_bw() +
  facet_grid(cols = vars(source))


aod_plot

```


```{r log sad area of difference}

log_sads <- all_sads %>%
  mutate(abund = log(abund))

log_sim_sads <- sim_sads %>%
  mutate(abund = log(abund))

log_aod <- log_sim_sads %>%
  group_by(sim, source) %>%
  summarize(emp = sum(abs(sort(abund) - sort(filter(log_sads, source == "emp")$abund))),
            flat = sum(abs(sort(abund) - sort(filter(log_sads, source == "flat")$abund))),
            stepwise = sum(abs(sort(abund) - sort(filter(log_sads, source == "stepwise")$abund))),
            exp = sum(abs(sort(abund) - sort(filter(log_sads, source == "exp")$abund))),
            precipice = sum(abs(sort(abund) - sort(filter(log_sads, source == "precipice")$abund)))) %>%
  ungroup() %>%
  tidyr::gather(-sim, -source, key = "comparison_source", value = "aod")

log_sim_bank <- log_sim_sads %>%
  mutate(sim = 1+ ((sim + 1) %% nsamples)) %>%
  rename(new_sim = sim)


sim_log_aod <- log_sim_sads %>%
  group_by(sim, source) %>%
  summarize(z_fs = sum(abs(sort(abund) - sort(filter(log_sim_bank, source == "fs", new_sim == sim)$abund))), 
           z_mete = sum(abs(sort(abund) - sort(filter(log_sim_bank, source == "mete", new_sim == sim)$abund)))) %>%
  ungroup() %>%
  tidyr::gather(-sim, -source, key = "comparison_source", value = "aod")


log_aod <- bind_rows(log_aod, sim_log_aod)


log_aod_plot <- ggplot(data = log_aod, aes(x = comparison_source, y = aod, color = comparison_source)) +
  geom_boxplot() +
  theme_bw() +
  facet_grid(cols = vars(source))


log_aod_plot

```