---
title: "Sensitivity"
author: "Renata Diaz"
date: "8/22/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(ggplot2)
library(meteR)
library(dplyr)
library(scads)

nsamples <- 100

save_samples <- T

```

```{r get some data, echo = F}

portal_data <- isds::get_toy_portal_data(download=T, years = c(1990:1995))

portal_sad <- portal_data %>%
  select(species) %>%
  group_by(species) %>%
  summarize(abund = n()) %>%
  ungroup() %>%
  select(abund) %>%
  arrange(abund) %>%
  as.matrix() %>%
  as.vector()

nspp = length(portal_sad)
nind = sum(portal_sad)

portal_sad <- data.frame(
  abund = portal_sad,
  source = "emp"
)


```

```{r make and plot extreme cases, echo = F}

flat <- portal_sad %>%
  mutate(source = "flat",
         abund = generate_even_sad(abund))

stepwise <- portal_sad %>%
  mutate(source = "stepwise",
         abund = generate_stepwise_sad(abund))

expesque <- portal_sad %>%
  mutate(source = "exp", 
         abund = generate_exponential_sad(abund))

prec <- portal_sad %>%
  mutate(source = "precipice",
         abund = generate_precipice_sad(abund))

all_sads <- bind_rows(portal_sad, flat, stepwise, expesque, prec) %>%
  group_by(source) %>%
  mutate(rank = row_number()) %>%
  ungroup()

all_sads_plot <- ggplot(data = all_sads, aes(x = rank, y = abund, color = source)) +
  geom_point() +
  facet_wrap(source ~ .) +
  theme_bw() +
  theme(legend.position = "none")



```

```{r generate and plot Leg coeffs, fig.dim= c(15, 6)}

legendre_estimates_list <- lapply(as.list(unique(all_sads$source)),
                             FUN = function(source_name) 
                               return(legendre_approx(filter(all_sads, source == source_name)$abund, nleg = 6)$coefficients)) 

names(legendre_estimates_list) <- unique(all_sads$source)

legendre_estimates <- bind_rows(legendre_estimates_list) %>%
  mutate(varname = names(legendre_estimates_list$emp),
         varindex = 1:length(legendre_estimates_list$emp)) %>%
  tidyr::gather(-varname, -varindex, key = "source", value = "coefficient")


coeffs_plot <- ggplot(data = legendre_estimates, aes(x = varindex, y = coefficient, color = source)) +
  geom_point() +
  geom_line() +
  scale_x_continuous(breaks = unique(legendre_estimates$varindex), labels = unique(legendre_estimates$varname)) +
    facet_wrap(source ~ .) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 75, hjust = 1),
        legend.position = "none")

gridExtra::grid.arrange(grobs = list(all_sads_plot, coeffs_plot), nrow = 1)

```


```{r draw and plot fs and mete corpuses}

set.seed(1977)

mete_samples <- sample_METE(s = nspp, n = nind, nsamples = nsamples, distinct = TRUE) %>%
  tidyr::gather(key = "sim", value = "abund") %>%
  dplyr::mutate(sim = as.integer(substr(sim, 2, nchar(sim))),
                source = "mete")

fs_samples <- sample_feasibleset(s = nspp, n = nind, nsamples = nsamples, distinct = TRUE) %>%
  tidyr::gather(key = "sim", value = "abund") %>%
  dplyr::mutate(sim = as.integer(substr(sim, 2, nchar(sim))),
                source = "fs")

sim_sads <- bind_rows(mete_samples, fs_samples) %>%
  group_by(sim, source) %>%
  mutate(rank = row_number()) %>%
  ungroup()

sample_plot <- ggplot(data = sim_sads, aes(x = rank, y = abund)) +
  geom_point(alpha = 0.05) +
  theme_bw() +
  facet_grid(cols = vars(source))

sample_plot

if(save_samples) {
  save(sim_sads, file = here::here("reports", "sensitivity_stash.Rds"))
}

```

```{r fit and plot sims}


sim_estimates_list <- apply(as.matrix(distinct(select(sim_sads, source, sim))),
                            MARGIN = 1,
                             FUN = function(sim_source) 
                               return(legendre_approx(filter(sim_sads, source == sim_source[1], sim == as.integer(sim_source[2]))$abund, nleg = 6)$coefficients))

sim_estimates <- t(sim_estimates_list) %>%
  as.data.frame() %>%
  mutate(sim_source = apply(as.matrix(distinct(select(sim_sads, source, sim))),
                            MARGIN = 1, FUN = function(sim_source) 
                               return(sim_source[1])),
         sim = apply(as.matrix(distinct(select(sim_sads, source, sim))),
                            MARGIN = 1, FUN = function(sim_source) 
                               return(as.integer(sim_source[2]))))
sim_estimates <- sim_estimates %>%
  tidyr::gather(-sim, -sim_source, key = "varname", value = "coefficient") %>%
  group_by(sim, sim_source) %>%
  mutate(varindex = row_number()) %>%
  ungroup()


leg_estimates_overlay <- bind_rows(
  mutate(legendre_estimates, sim_source = "mete"),
  mutate(legendre_estimates, sim_source = "fs")
)


sim_coeff_plot <- ggplot(data = sim_estimates, aes(x = varindex, y = coefficient)) + 
  geom_point(alpha = .05) +
  scale_x_continuous(breaks = unique(sim_estimates$varindex), labels = unique(sim_estimates$varname)) + 
  theme_bw() +
  facet_grid(cols = vars(sim_source)) +
  theme(axis.text.x = element_text(angle = 75, hjust = 1)) +
  geom_line(data = leg_estimates_overlay, aes(x = varindex, y = coefficient, color = source), size = 1)


sim_coeff_plot
```